name: ConsoleLogger
api: 1.6.0
main: hoyinm\consolelogger\ConsoleLogger
version: 1.0.1
author: hoyinm
description: Log player commands just like Bukkit Servers
website: http://www.cybercube-hk.com
Github: http://github.cybercube-hk.com